name: social_demo
version: "1.0"
config-version: 2

profile: social_demo

model-paths: ["models"]
seed-paths: ["seeds", "../../datasets"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  social_demo:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

seeds:
  social_demo:
    +quote_columns: false
